ALTER TABLE Rating
DROP FOREIGN KEY fkRatingImageId;

ALTER TABLE Rating
ADD CONSTRAINT fkRatingImageId
FOREIGN KEY ( ImageId )
REFERENCES Image ( Id )
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Rating
DROP FOREIGN KEY fkRatingUserId;

ALTER TABLE Rating
ADD CONSTRAINT fkRatingUserId
FOREIGN KEY ( UserId )
REFERENCES User ( Id )
ON DELETE CASCADE
ON UPDATE CASCADE;
